import type { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Headset HyperX Cloud II',
    description: 'Headset gamer com som surround 7.1, almofadas de espuma viscoelástica e microfone removível com cancelamento de ruído.',
    category: 'Headsets',
    image_url: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400&q=80',
    available: true,
    specs: { 'Conexão': 'USB / 3.5mm', 'Driver': '53mm', 'Resposta de freq.': '15Hz–25kHz' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Mouse Logitech MX Master 3',
    description: 'Mouse ergonômico de alta performance com scroll MagSpeed, rastreamento em qualquer superfície e botões programáveis.',
    category: 'Mouses',
    image_url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80',
    available: true,
    specs: { 'Conexão': 'Bluetooth / USB', 'DPI': 'até 4000', 'Bateria': '70 dias' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Mousepad Redragon P001 XXL',
    description: 'Mousepad de tecido premium extra grande com base antiderrapante e bordas costuradas para maior durabilidade.',
    category: 'Mousepads',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80',
    available: true,
    specs: { 'Dimensões': '900 × 400mm', 'Espessura': '3mm', 'Material': 'Tecido premium' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Monitor LG 27" 4K IPS',
    description: 'Monitor UltraFine 4K com painel IPS, HDR400, cobertura sRGB 99% e saídas USB-C com carregamento 96W.',
    category: 'Monitores',
    image_url: 'https://images.unsplash.com/photo-1527443224154-c4a573d5e27f?w=400&q=80',
    available: true,
    specs: { 'Resolução': '3840×2160', 'Painel': 'IPS', 'Refresh': '60Hz', 'HDR': 'HDR400' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Hub USB-C Anker 7-em-1',
    description: 'Hub compacto com HDMI 4K, 3x USB-A, USB-C dados, SD e microSD. Ideal para notebooks com poucas portas.',
    category: 'Hubs USB',
    image_url: 'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=400&q=80',
    available: true,
    specs: { 'Portas': '7', 'HDMI': '4K@30Hz', 'USB-A': '3× USB 3.0', 'Cartões': 'SD + microSD' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Teclado Keychron K2 Wireless',
    description: 'Teclado mecânico compacto 75% com switches ópticos, retroiluminação RGB e compatibilidade Mac/Windows.',
    category: 'Teclados',
    image_url: 'https://images.unsplash.com/photo-1561112078-7d24e04c3407?w=400&q=80',
    available: true,
    specs: { 'Layout': '75% (84 teclas)', 'Conexão': 'Bluetooth / USB-C', 'Bateria': '4000mAh' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Webcam Logitech C920 HD Pro',
    description: 'Webcam Full HD 1080p com autofoco, som estéreo e campo de visão 78° para videoconferências nítidas.',
    category: 'Webcams',
    image_url: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&q=80',
    available: false,
    specs: { 'Resolução': '1080p/30fps', 'Campo visão': '78°', 'Microfone': 'Estéreo embutido' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Monitor Dell 24" Full HD',
    description: 'Monitor profissional com painel IPS slim bezel, ajuste de altura, pivô e saídas HDMI/DisplayPort.',
    category: 'Monitores',
    image_url: 'https://images.unsplash.com/photo-1547119957-637f8679db1e?w=400&q=80',
    available: true,
    specs: { 'Resolução': '1920×1080', 'Painel': 'IPS', 'Refresh': '75Hz', 'Conexões': 'HDMI + DP' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
